Controllers/CourseDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DF984515MIS4200.DAL;
using DF984515MIS4200.Models;

namespace DF984515MIS4200.Controllers
{
    public class CourseDetailsController : Controller
    {
        private MIS4200Context db = new MIS4200Context();

        // GET: CourseDetails
        public ActionResult Index()
        {
            var courseDetails = db.CourseDetails.Include(c => c.Course).Include(c => c.Student);
            return View(courseDetails.ToList());
        }

        // GET: CourseDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseDetail courseDetail = db.CourseDetails.Find(id);
            if (courseDetail == null)
            {
                return HttpNotFound();
            }
            return View(courseDetail);
        }

        // GET: CourseDetails/Create
        public ActionResult Create()
        {
            ViewBag.courseID = new SelectList(db.Courses, "courseID", "courseName");
            ViewBag.studentID = new SelectList(db.Students, "studentID", "fullName");
            return View();
        }

        // POST: CourseDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "coursedetailID,startDate,endDate,location,courseID,studentID")] CourseDetail courseDetail)
        {
            if (ModelState.IsValid)
            {
                db.CourseDetails.Add(courseDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.courseID = new SelectList(db.Courses, "courseID", "courseName", courseDetail.courseID);
            ViewBag.studentID = new SelectList(db.Students, "studentID", "fullName", courseDetail.studentID);
            return View(courseDetail);
        }

        // GET: CourseDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseDetail courseDetail = db.CourseDetails.Find(id);
            if (courseDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.courseID = new SelectList(db.Courses, "courseID", "courseName", courseDetail.courseID);
            ViewBag.studentID = new SelectList(db.Students, "studentID", "fullName", courseDetail.studentID);
            return View(courseDetail);
        }

        // POST: CourseDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "coursedetailID,startDate,endDate,location,courseID,studentID")] CourseDetail courseDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.courseID = new SelectList(db.Courses, "courseID", "courseName", courseDetail.courseID);
            ViewBag.studentID = new SelectList(db.Students, "studentID", "firstName", courseDetail.studentID);
            return View(courseDetail);
        }

        // GET: CourseDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseDetail courseDetail = db.CourseDetails.Find(id);
            if (courseDetail == null)
            {
                return HttpNotFound();
            }
            return View(courseDetail);
        }

        // POST: CourseDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseDetail courseDetail = db.CourseDetails.Find(id);
            db.CourseDetails.Remove(courseDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DF984515MIS4200.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About Me";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>
    I am a senior pursuing my bachelor's degree in Business Administration at Ohio University. 
    To be more specific, I am studying Economics, Management Information Systems, & Data Analytics. 
    My studies allow me to uncover the relationships between things both in personal and professional settings which gives me a better understanding of the world.
    My time at Ohio University has allowed me to develop myself in many ways. 
    I have had the opportunity to not only join several selective organizations on campus but also hold leadership positions within these organizations. 
    I am proud to have made an impact on these organizations and make sure that they are better when I leave them compared to when I joined them. 
    All of these organizations have honed my business skills, taught me valuable life lessons, and built my leadership.
    Through my coursework, organizations, and previous work experience, I strive to perform at my highest level at all times! 
    I will be starting my career as a junior search consultant at Alliance Search Solutions in May 2020!
</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Information";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    25 Kurtz Street<br />
    Apartment 210<br />
    Athens, OH 45701<br />    
</address>

<address>
    <strong>Phone:</strong> 216.978.5782<br />
    <strong>Email:</strong> <a href="mailto:df984515@ohio.edu">df984515@ohio.edu</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />
<div class="jumbotron">
    <h1>Dan Foster</h1>
    <p class="lead">Hey there! Welcome to my website for MIS4200. Feel free to look around and if you want to know a little bit about me, check out some quick facts below!</p>
    <p><a href="https://www.linkedin.com/in/daniel-t-foster/" class="btn btn-primary btn-lg">My LinkedIn &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Past</h2>
        <p>
            I am from Cleveland, Ohio and have lived in Rocky River for the past 8 years now.
            I have two older brothers and one younger sister aged 28, 26, and 14, respectively.
            I also have three animals: Jackson my lab-terrier mix, Memphis my tabby cat, and Blu my Siamese cat.
        </p>
    </div>
    <div class="col-md-3">
        <h2>Present</h2>
        <p>
            I am a senior in the College of Business here at Ohio University.
            I am triple majoring in Economics, Management Information Systems, and Analytics.
            I am a part of a couple organizations here on campus: Alpha Kappa Psi Professional Business Fraternity, and the Emerging Leaders Program.
        </p>
    </div>
    <div class="col-md-3">
        <h2>Future</h2>
        <p>
            I plan on graduating in May of this year with my bachelors of business administration and I will hopefully graduate with high honors.
            After graduation, I am moving back to Cleveland to work as a search consultant for Alliance Search Solutions, based out of Independence, Ohio.
        </p>
    </div>
    <div class="col-md-3">
        <h2>Links</h2>
        <p>
            The following are links to all of the pages on this website. Definitely feel free to explore and fiddle with items on each page!
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            <li>@Html.ActionLink("Instructors", "Index", "Instructors")</li>
            <li>@Html.ActionLink("Students", "Index", "Students")</li>
            <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
            <li>@Html.ActionLink("Course Details", "Index", "CourseDetails")</li>
        </p>
    </div>
</div>